cask "dwmac" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.1.1'
  sha256 "3d34c43d6fd7d3f79e8907e6633118293d33a39d7d9b42902d606f482673efb6"

  url "https://github.com/hillyu/dwmac/releases/download/v#{version}/Dwmac-v#{version}.zip"
  name "Dwmac"
  desc "Dwmac is an i3-like tiling window manager for macOS"
  homepage "https://github.com/hillyu/Dwmac"
  conflicts_with cask: 'dwmac-dev'

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/Dwmac-v#{version}/bin/dwmac"
    system "xattr -d com.apple.quarantine #{appdir}/Dwmac.app"
  end

  app "Dwmac-v#{version}/Dwmac.app"
  binary "Dwmac-v#{version}/bin/dwmac"

  binary "Dwmac-v#{version}/shell-completion/zsh/_dwmac",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_dwmac"
  binary "Dwmac-v#{version}/shell-completion/bash/dwmac",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/dwmac"
  binary "Dwmac-v#{version}/shell-completion/fish/dwmac.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/dwmac.fish"

  Dir["#{staged_path}/Dwmac-v#{version}/manpage/*"].each { |man| manpage man }
end
