cask "dwmac@0.2.1" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.2.1'
  sha256 "fc3b7157161afc0ed3abb24b29c298392827ad38a89a819f15f1ef87f6c46fdb"

  url "https://github.com/hillyu/dwmac/releases/download/v#{version}/Dwmac-v#{version}.zip"
  name "Dwmac"
  desc "Dwmac is an i3-like tiling window manager for macOS"
  homepage "https://github.com/hillyu/Dwmac"
  conflicts_with cask: ['dwmac', 'dwmac-dev']

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/Dwmac-v#{version}/bin/dwmac"
    system "xattr -d com.apple.quarantine #{appdir}/Dwmac.app"
  end

  app "Dwmac-v#{version}/Dwmac.app"
  binary "Dwmac-v#{version}/bin/dwmac"

  binary "Dwmac-v#{version}/shell-completion/zsh/_dwmac",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_dwmac"
  binary "Dwmac-v#{version}/shell-completion/bash/dwmac",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/dwmac"
  binary "Dwmac-v#{version}/shell-completion/fish/dwmac.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/dwmac.fish"

  Dir["#{staged_path}/Dwmac-v#{version}/manpage/*"].each { |man| manpage man }
end
