cask "dwmac" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.2.0'
  sha256 "ac1b6b7a14680b9f9226105e60130b4f8b895a956c9585ab3af9d65654d15dfa"

  url "https://github.com/hillyu/dwmac/releases/download/v#{version}/Dwmac-v#{version}.zip"
  name "Dwmac"
  desc "Dwmac is an i3-like tiling window manager for macOS"
  homepage "https://github.com/hillyu/Dwmac"
  conflicts_with cask: 'dwmac-dev'

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/Dwmac-v#{version}/bin/dwmac"
    system "xattr -d com.apple.quarantine #{appdir}/Dwmac.app"
  end

  app "Dwmac-v#{version}/Dwmac.app"
  binary "Dwmac-v#{version}/bin/dwmac"

  binary "Dwmac-v#{version}/shell-completion/zsh/_dwmac",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_dwmac"
  binary "Dwmac-v#{version}/shell-completion/bash/dwmac",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/dwmac"
  binary "Dwmac-v#{version}/shell-completion/fish/dwmac.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/dwmac.fish"

  Dir["#{staged_path}/Dwmac-v#{version}/manpage/*"].each { |man| manpage man }
end
